// =================================================================
// CURRICULUM_DATA — single source of truth for ALL lesson content.
// Add or edit lesson content here. Screens read it via getUnitData(unit, level).
// =================================================================
export const CURRICULUM_DATA: any = {
  level_2: {
    unit_5: {
      title: "I Can Do It!",
      icon: "💪",
      grammarGameMode: "GRAMMAR_ORBIT",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "fly", vn: "bay", emoji: "🕊️" },
          { word: "write", vn: "viết", emoji: "✍️" },
          { word: "draw", vn: "vẽ", emoji: "✏️" },
          { word: "jump", vn: "nhảy", emoji: "🤸" },
          { word: "walk", vn: "đi bộ", emoji: "🚶" },
          { word: "swim", vn: "bơi", emoji: "🏊" },
          { word: "read", vn: "đọc", emoji: "📖" },
          { word: "run", vn: "chạy", emoji: "🏃" },
        ],
        lesson_5: [
          "throw a ball",
          "catch a ball",
          "ride a bike",
          "drive a car",
          "use a computer",
          "play the guitar",
          "jump rope",
          "climb a tree",
        ],
      },
      grammar: {
        willWont: [
          { before: "You", after: "draw and write.", answer: "can" },
          { before: "I can draw, but I", after: "fly.", answer: "can't" },
          { before: "The artist can draw, but he", after: "fly.", answer: "can't" },
          { before: "Can you climb a tree? Yes, I", after: ".", answer: "can" },
          { before: "Can you jump rope? No, I", after: ".", answer: "can't" },
          { before: "Dan can run and jump, but he", after: "swim.", answer: "can't" },
          { before: "The teacher", after: "write and read.", answer: "can" },
          { before: "Can she jump rope? No, she", after: ".", answer: "can't" },
        ],
      },
      ai_speak: [
        "You can draw well, Dan! That's nice.",
        "I can draw, but I can't fly!",
        "Can you climb a tree? Yes, I can. Look!",
        "Can you jump rope? No, I can't.",
        "Dan can run and jump, but he can't swim. You can do it!",
      ],
      reading: {
        text: "Let's Play! Many sports use a ball and a team. Basketball has five boys or girls on a team. They use a big ball and a very tall net. Can you throw and bounce a ball? Basketball is for you! Baseball has nine players on a team. They use a small white ball and a bat. Can you hit and catch a ball? Baseball is for you! Hockey has six players on a team. They use ice skates, a hockey stick, and a net. Can you skate? Hockey is for you!",
        questions: [
          { q: "A basketball team has five players.", a: true },
          { q: "Baseball players use a hockey stick.", a: false },
          { q: "Hockey players use ice skates.", a: true },
        ],
      },
    },
    unit_6: {
      title: "My Day",
      icon: "🌞",
      formToggleLabel: "Ngôi 3 +s ⬆️",
      grammarGameMode: "COSMIC_BALLOON_POP",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "get up", alt: "gets up", vn: "thức dậy", emoji: "⏰" },
          { word: "eat breakfast", alt: "eats breakfast", vn: "ăn sáng", emoji: "🍳" },
          { word: "go to school", alt: "goes to school", vn: "đi học", emoji: "🏫" },
          { word: "eat lunch", alt: "eats lunch", vn: "ăn trưa", emoji: "🍱" },
          { word: "go home", alt: "goes home", vn: "về nhà", emoji: "🏠" },
          { word: "eat dinner", alt: "eats dinner", vn: "ăn tối", emoji: "🍽️" },
          { word: "brush my teeth", alt: "brushes my teeth", vn: "đánh răng", emoji: "🪥" },
          { word: "go to bed", alt: "goes to bed", vn: "đi ngủ", emoji: "🛏️" },
        ],
        lesson_5: [
          "eight o'clock",
          "half past nine",
          "a quarter after one",
          "a quarter to two",
          "nine thirty",
          "one fifteen",
          "one forty-five",
        ],
      },
      ai_speak: [
        "What do you do in the morning? I get up and eat breakfast.",
        "Then I go to school.",
        "What time is it? It's nine o'clock.",
        "When does May go to bed? She goes to bed at eight thirty.",
        "When do you get up? I get up at seven o'clock.",
      ],
      reading: {
        text: "Night and Day! Hiro is from Japan. He lives in Tokyo. Megan is from Canada. She lives in Toronto. Right now it's night in Japan, but in Canada it's morning. Hiro is asleep, and Megan is awake. Megan eats breakfast at 7:00 every day. She goes to school at 8:30 and goes home at 3:30. When it's morning in Japan, Hiro eats breakfast at 7:30. He goes to school at 8:30, too. Hiro and Megan live in different time zones, but their days are almost the same!",
        questions: [
          { q: "Hiro lives in Tokyo.", a: true },
          { q: "Megan goes to school at 8:30.", a: true },
          { q: "Hiro and Megan live in the same time zone.", a: false },
        ],
      },
    },
    unit_7: {
      title: "Playtime!",
      icon: "🎮",
      grammarGameMode: "ROCKET_BLASTER",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "playing soccer", vn: "chơi bóng đá", emoji: "⚽" },
          { word: "playing tennis", vn: "chơi quần vợt", emoji: "🎾" },
          { word: "watching TV", vn: "xem TV", emoji: "📺" },
          { word: "playing video games", vn: "chơi trò chơi điện tử", emoji: "🎮" },
          { word: "reading books", vn: "đọc sách", emoji: "📚" },
          { word: "listening to music", vn: "nghe nhạc", emoji: "🎵" },
          { word: "taking photos", vn: "chụp ảnh", emoji: "📸" },
        ],
        lesson_5: [
          "singing",
          "dancing",
          "writing stories",
          "drawing",
          "playing the piano",
          "playing board games",
          "baking cookies",
        ],
      },
      grammar: {
        willWont: [
          { before: "What do you", after: "doing? I like tennis.", answer: "like" },
          { before: "Do you like playing tennis? Yes, I", after: ".", answer: "do" },
          { before: "Do you like playing video games? No, I", after: ".", answer: "don't" },
          { before: "What does she", after: "doing? She likes drawing.", answer: "like" },
          { before: "She", after: "drawing.", answer: "likes" },
          { before: "Does he like singing? Yes, he", after: ".", answer: "does" },
          { before: "Does she like dancing? No, she", after: ".", answer: "doesn't" },
          { before: "He", after: "playing soccer.", answer: "likes" },
        ],
      },
      ai_speak: [
        "What do you like doing? I like playing tennis.",
        "Do you like playing soccer? Yes, I do.",
        "I like reading books. I don't like playing video games.",
        "What does she like doing? She likes drawing.",
        "Does he like singing? No, he doesn't. He likes dancing.",
      ],
      reading: {
        text: "Make Some Music! Emily likes singing and playing the guitar. A guitar has six strings. Play the strings and make some music! Kevin likes playing the piano. A piano has 52 white keys and 36 black keys. You press the keys, and the keys hit the strings inside. Steven likes playing the flute. There are eight holes in a flute. Blow in the flute, press your fingers on the holes, and make some music!",
        questions: [
          { q: "A guitar has six strings.", a: true },
          { q: "A flute has ten holes.", a: false },
          { q: "You press the keys on a piano.", a: true },
        ],
      },
    },
    unit_2: {
      title: "My Things",
      icon: "🧸",
      grammarGameMode: "ROCKET_BLASTER",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "teddy bear", vn: "gấu bông", emoji: "🧸" },
          { word: "camera", vn: "máy ảnh", emoji: "📷" },
          { word: "scooter", vn: "xe trượt scooter", emoji: "🛴" },
          { word: "train", vn: "tàu hỏa (đồ chơi)", emoji: "🚂" },
          { word: "yo-yo", vn: "con quay yo-yo", emoji: "🪀" },
          { word: "skateboard", vn: "ván trượt", emoji: "🛹" },
          { word: "board game", vn: "trò chơi cờ bàn", emoji: "🎲" },
          { word: "video game", vn: "trò chơi điện tử", emoji: "🎮" },
        ],
        lesson_5: ["bag", "tablet", "paintbrush", "scissors", "marker", "paint", "glue", "photo"],
      },
      grammar: {
        willWont: [
          { before: "Look at Alex! That's", after: "camera.", answer: "his" },
          { before: "Look at Eva! Those are", after: "teddy bears.", answer: "her" },
          { before: "Look at Bobby and Eva! Those are", after: "yo-yos.", answer: "their" },
          { before: "Is this", after: "bag? No, it isn't.", answer: "your" },
          { before: "Those are", after: "things, not yours!", answer: "our" },
          { before: "That's", after: "train. It's Alex's.", answer: "his" },
          { before: "Are these", after: "scissors?", answer: "your" },
          { before: "Those are", after: "board games.", answer: "her" },
        ],
      },
      ai_speak: [
        "Look at Alex! That's his new camera.",
        "Those are her teddy bears. That's cute!",
        "Is this your bag? No, it isn't.",
        "Can I borrow it? Sure! Ask first.",
        "Those are our scooters. You can use them, but please ask first.",
      ],
      reading: {
        text: "Fun with Colors! You can mix colors to make new colors. Mix blue and yellow to make green. Mix red and yellow to make orange. Mix red and blue to make purple. An artist uses paint and a paintbrush to make a painting. You can also make a collage with paper, paint, scissors, and glue. There are many colors all around us. How many can you find?",
        questions: [
          { q: "Blue and yellow make green.", a: true },
          { q: "Red and blue make orange.", a: false },
          { q: "You can make a collage with paper and glue.", a: true },
        ],
      },
    },
    unit_3: {
      title: "At the Zoo",
      icon: "🐘",
      formToggleLabel: "Số nhiều +s ⬆️",
      grammarGameMode: "COSMIC_BALLOON_POP",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "elephant", alt: "elephants", vn: "con voi", emoji: "🐘" },
          { word: "zebra", alt: "zebras", vn: "con ngựa vằn", emoji: "🦓" },
          { word: "giraffe", alt: "giraffes", vn: "con hươu cao cổ", emoji: "🦒" },
          { word: "monkey", alt: "monkeys", vn: "con khỉ", emoji: "🐒" },
          { word: "hippo", alt: "hippos", vn: "con hà mã", emoji: "🦛" },
          { word: "crocodile", alt: "crocodiles", vn: "con cá sấu", emoji: "🐊" },
          { word: "tiger", alt: "tigers", vn: "con hổ", emoji: "🐯" },
        ],
        lesson_5: ["beach", "bookstore", "mall", "playground", "school", "swimming pool", "zoo"],
      },
      ai_speak: [
        "Is there a monkey? Yes, there is.",
        "Are there hippos at this zoo? Yes, there are.",
        "Is there an elephant? No, there isn't.",
        "Where's the playground? It's in front of the zoo.",
        "Where's the bookstore? It's between the zoo and the mall.",
      ],
      reading: {
        text: "Baby Animals! A mother crocodile is a good mother. Her body is about three meters long, from her head to her tail. Her babies hatch from eggs. A baby giraffe is very tall. Giraffes have long legs and a long neck. The mother giraffe eats leaves from the trees and gives milk to her baby. A baby monkey has two arms, two legs, and a very long tail. Monkeys climb trees with their arms, legs, and tails.",
        questions: [
          { q: "Baby crocodiles hatch from eggs.", a: true },
          { q: "Giraffes have short necks.", a: false },
          { q: "Monkeys climb trees with their tails.", a: true },
        ],
      },
    },
    unit_4: {
      title: "Yummy Food!",
      icon: "🍉",
      grammarGameMode: "GRAMMAR_ORBIT",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "pineapple", vn: "quả dứa", emoji: "🍍" },
          { word: "pear", vn: "quả lê", emoji: "🍐" },
          { word: "apple", vn: "quả táo", emoji: "🍎" },
          { word: "kiwi", vn: "quả kiwi", emoji: "🥝" },
          { word: "watermelon", vn: "quả dưa hấu", emoji: "🍉" },
          { word: "orange", vn: "quả cam", emoji: "🍊" },
          { word: "coconut", vn: "quả dừa", emoji: "🥥" },
          { word: "banana", vn: "quả chuối", emoji: "🍌" },
        ],
        lesson_5: ["burger", "corn", "egg", "French fries", "pancakes", "pie", "sandwich", "soup"],
      },
      grammar: {
        willWont: [
          { before: "Does Dan like bananas? Yes, he", after: ".", answer: "does" },
          { before: "Does Nancy like apples? Yes, she", after: ".", answer: "does" },
          { before: "Does he like pie? No, he", after: ".", answer: "doesn't" },
          { before: "What", after: "you want for lunch?", answer: "do" },
          { before: "I", after: "eggs and pancakes, please.", answer: "want" },
          { before: "Does she like pears? Yes, she", after: ".", answer: "does" },
          { before: "Do you like soup? No, I", after: ".", answer: "don't" },
          { before: "What do you", after: "for dinner?", answer: "want" },
        ],
      },
      ai_speak: [
        "Does Dan like bananas? Yes, he does.",
        "Does Nancy like apples? Yes, she does.",
        "What do you want for breakfast? I want eggs and pancakes, please.",
        "What do you want for dinner? I want a burger and pie, please.",
        "Do you like soup? No, I don't.",
      ],
      reading: {
        text: "Life Cycle of a Fruit! This is the life cycle of a watermelon. A watermelon seed is small and black. The seed grows into a plant. The plant is green, and it grows big. Then the plant grows flowers, and the flowers become fruit. The fruit has many seeds inside. The seeds fall on the ground, and they grow into more watermelons. Watermelons are green and red. They are big and have a lot of juice. They are very healthy and yummy!",
        questions: [
          { q: "A watermelon seed grows into a plant.", a: true },
          { q: "Watermelons are small and dry.", a: false },
          { q: "A watermelon has seeds inside.", a: true },
        ],
      },
    },
    unit_1: {
      title: "On the Farm",
      icon: "🐄",
      formToggleLabel: "Số nhiều +s ⬆️",
      grammarGameMode: "ROCKET_BLASTER",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "donkey", alt: "donkeys", vn: "con lừa", emoji: "🫏" },
          { word: "horse", alt: "horses", vn: "con ngựa", emoji: "🐴" },
          { word: "goat", alt: "goats", vn: "con dê", emoji: "🐐" },
          { word: "duck", alt: "ducks", vn: "con vịt", emoji: "🦆" },
          { word: "sheep", alt: "sheep", vn: "con cừu", emoji: "🐑" },
          { word: "cow", alt: "cows", vn: "con bò", emoji: "🐄" },
          { word: "chicken", alt: "chickens", vn: "con gà", emoji: "🐔" },
          { word: "caterpillar", alt: "caterpillars", vn: "con sâu bướm", emoji: "🐛" },
          { word: "butterfly", alt: "butterflies", vn: "con bướm", emoji: "🦋" },
          { word: "bee", alt: "bees", vn: "con ong", emoji: "🐝" },
          { word: "mosquito", alt: "mosquitos", vn: "con muỗi", emoji: "🦟" },
          { word: "ladybug", alt: "ladybugs", vn: "con bọ rùa", emoji: "🐞" },
          { word: "ant", alt: "ants", vn: "con kiến", emoji: "🐜" },
        ],
        lesson_5: ["spider", "legs", "wings", "eyes", "open", "closed"],
      },
      grammar: {
        willWont: [
          { before: "What's this? It's a", after: ".", answer: "goat" },
          { before: "What's that? It's a", after: ".", answer: "duck" },
          { before: "What's this? It's a", after: ".", answer: "sheep" },
          { before: "What's that? It's a", after: ".", answer: "cow" },
          { before: "What are these? They're", after: ".", answer: "bees" },
          { before: "What are those? They're", after: ".", answer: "ants" },
          { before: "What are these? They're", after: ".", answer: "butterflies" },
          { before: "What are those? They're", after: ".", answer: "mosquitos" },
        ],
      },
      ai_speak: [
        "What's this? It's a sheep.",
        "What's that? It's a cow.",
        "What are these? They're butterflies.",
        "What are those? They're bees.",
        "Look! What's that? It's a baby duck. It's cute!",
      ],
      reading: {
        text: "Bugs Are Great! Bugs are small, but they are amazing. A spider has eight legs and eight eyes. A spider is not an insect! A butterfly has six legs and big, colorful wings. When the wings are open, you can see the bright colors. A bee is yellow, brown, and black. It has six legs, four wings, and many eyes. You can find bugs in your garden, on trees, and under leaves. Look closely. How many can you find?",
        questions: [
          { q: "A spider has eight legs.", a: true },
          { q: "A butterfly has no wings.", a: false },
          { q: "You can find bugs under leaves.", a: true },
        ],
      },
    },
  },
  level_4: {
    unit_7: {
      title: "Outdoor Fun",
      icon: "🛹",
      formToggleLabel: "Comparative ⬆️",
      grammarGameMode: "COSMIC_BALLOON_POP",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "exciting", alt: "more exciting", vn: "thú vị / hào hứng", emoji: "🤩" },
          { word: "boring", alt: "more boring", vn: "chán / nhàm chán", emoji: "😴" },
          { word: "dangerous", alt: "more dangerous", vn: "nguy hiểm", emoji: "⚠️" },
          { word: "difficult", alt: "more difficult", vn: "khó", emoji: "😣" },
          { word: "easy", alt: "easier", vn: "dễ", emoji: "😎" },
          { word: "fun", alt: "more fun", vn: "vui", emoji: "😄" },
        ],
        lesson_5: ["snowboarding", "sailing", "rock climbing", "golfing", "skydiving", "scuba diving"],
      },
      ai_speak: [
        "Juggling is more difficult than riding a bicycle.",
        "Skateboarding is more boring than juggling.",
        "Roller skating is easier than skateboarding.",
        "Which one is the most exciting? I think skydiving is the most exciting.",
        "Golfing is the most boring activity.",
      ],
      reading: {
        text: "Be Safe: Riding a bicycle, roller skating, and skateboarding are fun, but they can be dangerous. Here are some ways to stay safe. When you ride a bicycle, always wear a helmet. Wear colorful clothes so drivers can see you, and use lights at night. Never listen to music on the road, and always stop when you see a stop sign. When you skateboard or roller skate, never skate on the road. A park is much safer! Always wear a helmet to protect your head, and wear elbow pads and knee pads to protect your arms and legs. Have fun and be safe!",
        questions: [
          { q: "You should always wear a helmet when you ride a bicycle.", a: true },
          { q: "It is safe to skateboard on the road.", a: false },
          { q: "Elbow pads and knee pads protect your arms and legs.", a: true },
        ],
      },
    },
    unit_8: {
      title: "Summer Vacation",
      icon: "🏖️",
      grammarGameMode: "ROCKET_BLASTER",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "feed my hamster", vn: "cho chuột hamster ăn", emoji: "🐹" },
          { word: "make my bed", vn: "dọn giường", emoji: "🛏️" },
          { word: "find my swimsuit", vn: "tìm đồ bơi", emoji: "🩱" },
          { word: "clean my room", vn: "dọn phòng", emoji: "🧹" },
          { word: "pack my suitcase", vn: "soạn va li", emoji: "🧳" },
          { word: "help my parents", vn: "giúp bố mẹ", emoji: "🤝" },
        ],
        lesson_5: [
          "go to a water park",
          "learn to surf",
          "look for seashells",
          "sell lemonade",
          "stay in a hotel",
          "visit family",
        ],
      },
      grammar: {
        willWont: [
          { before: "Before vacation, I have to pack my", after: ".", answer: "suitcase" },
          { before: "Clara has to feed her", after: ".", answer: "hamster" },
          { before: "I have to clean my", after: ".", answer: "room" },
          { before: "This summer, I'm going to visit", after: ".", answer: "family" },
          { before: "Sid is going to sell", after: ".", answer: "lemonade" },
          { before: "We're going to learn to", after: ".", answer: "surf" },
        ],
      },
      ai_speak: [
        "I have to pack my suitcase before vacation.",
        "Do you have to feed your hamster? Yes, I do.",
        "What are you going to do this summer? I'm going to visit family.",
        "What's Sid going to do? He's going to sell lemonade.",
        "I'm not going to visit family. I'm going to learn to surf.",
      ],
      reading: {
        text: "Wonder Water Park: Come to Wonder Water Park, the biggest water park in the country! There are lots of things to do. You can play in the wave pool. It is cheap, and one hour costs only four dollars. You can also learn to surf. A surfing lesson costs ten dollars per hour. The park has three exciting water slides. The Mega Slide is the longest. It is 300 meters long, and one hour on it costs five dollars. You can relax on the slow Lazy River, too. Swimming makes you hungry, so you can buy pizza, sandwiches, and ice cream. Come and have fun!",
        questions: [
          { q: "Wonder Water Park is the biggest water park in the country.", a: true },
          { q: "The Mega Slide is the shortest water slide.", a: false },
          { q: "You can learn to surf at the water park.", a: true },
        ],
      },
    },
    unit_5: {
      title: "History Museum",
      icon: "🏛️",
      grammarGameMode: "ROCKET_BLASTER",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "scientist", vn: "nhà khoa học", emoji: "🔬" },
          { word: "soccer player", vn: "cầu thủ bóng đá", emoji: "⚽" },
          { word: "movie star", vn: "ngôi sao điện ảnh", emoji: "🎬" },
          { word: "painter", vn: "họa sĩ", emoji: "🎨" },
          { word: "pop star", vn: "ca sĩ nhạc pop", emoji: "🎤" },
          { word: "photographer", vn: "nhiếp ảnh gia", emoji: "📷" },
          { word: "nurse", vn: "y tá", emoji: "🩺" },
        ],
        lesson_5: [
          "tie my shoes",
          "play an instrument",
          "speak English",
          "whistle a tune",
          "use a smartphone",
          "do a cartwheel",
        ],
      },
      grammar: {
        willWont: [
          { before: "Mary Miller was a", after: ".", answer: "photographer" },
          { before: "Bill Brown was a", after: ".", answer: "painter" },
          { before: "Sue Smith was a", after: ".", answer: "nurse" },
          { before: "Rose Red was a", after: ".", answer: "movie star" },
          { before: "Barry Baker was a", after: ".", answer: "pop star" },
          { before: "Larry Lopez was a", after: ".", answer: "soccer player" },
          { before: "Hannah Harris was a", after: ".", answer: "scientist" },
        ],
      },
      ai_speak: [
        "Who was Mary Miller? She was a photographer.",
        "What did she do? She took photos of animals.",
        "Who was Bill Brown? He was a painter.",
        "Could you tie your shoes when you were three? No, I couldn't.",
        "Could you use a smartphone when you were five? Yes, I could.",
      ],
      reading: {
        text: "Brilliant Musicians: Mozart and Beethoven were great musicians. They made music a long time ago, but it is still popular today. Mozart could play the piano when he was five years old. He played at concerts when he was six, and he wrote music when he was eight. When Mozart was thirty-one, a young musician named Beethoven wanted to meet him. Beethoven could play the piano and the violin when he was young. He liked Mozart's music very much. Later, something terrible happened. When Beethoven was thirty-one, he could not hear his music anymore. He was very sad, but he still made beautiful music for many years.",
        questions: [
          { q: "Mozart could play the piano when he was five.", a: true },
          { q: "Beethoven could play the piano and the violin.", a: true },
          { q: "Beethoven could hear his music when he was thirty-one.", a: false },
        ],
      },
    },
    unit_6: {
      title: "In the Forest",
      icon: "🌲",
      formToggleLabel: "Comparative -er ⬆️",
      grammarGameMode: "COSMIC_BALLOON_POP",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "small", alt: "smaller", vn: "nhỏ", emoji: "🐜" },
          { word: "big", alt: "bigger", vn: "to / lớn", emoji: "🐘" },
          { word: "fast", alt: "faster", vn: "nhanh", emoji: "🐆" },
          { word: "slow", alt: "slower", vn: "chậm", emoji: "🐌" },
          { word: "cute", alt: "cuter", vn: "dễ thương", emoji: "🐰" },
          { word: "tall", alt: "taller", vn: "cao", emoji: "🦒" },
          { word: "strong", alt: "stronger", vn: "khỏe / mạnh", emoji: "💪" },
          { word: "loud", alt: "louder", vn: "ồn / to tiếng", emoji: "🔊" },
        ],
        lesson_5: ["owl", "wolf", "deer", "rabbit", "fox", "snail", "beetle", "raccoon"],
      },
      ai_speak: [
        "A fox is cuter than a wolf.",
        "Sid is faster than a bee.",
        "A wolf is bigger than an owl.",
        "A rabbit is faster than a snail.",
        "I think the owl is the prettiest.",
      ],
      reading: {
        text: "Night Owls: Owls are nocturnal animals. They sleep in the day and hunt at night. Their big eyes help them see very well in the dark. There are many different species of owls. The eagle owl is one of the biggest. It is about 75 centimeters tall and lives in a forest. At night, it hunts fish, snakes, and rabbits. The burrowing owl is one of the strangest. It is smaller than the eagle owl and sleeps in a hole in the ground. It has long legs and can run very fast. The elf owl is the smallest of all. It is only 15 centimeters tall, and at night it hunts insects and lizards.",
        questions: [
          { q: "Owls sleep in the day and hunt at night.", a: true },
          { q: "The elf owl is the biggest owl species.", a: false },
          { q: "The burrowing owl can run very fast.", a: true },
        ],
      },
    },
    unit_4: {
      title: "Last Weekend",
      icon: "🎬",
      formToggleLabel: "Past Form ⏳",
      grammarGameMode: "ROCKET_BLASTER",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "buy candy", alt: "bought candy", vn: "mua kẹo", emoji: "🍬" },
          { word: "see a movie", alt: "saw a movie", vn: "xem phim", emoji: "🎬" },
          { word: "take a picture", alt: "took a picture", vn: "chụp ảnh", emoji: "📷" },
          { word: "go shopping", alt: "went shopping", vn: "đi mua sắm", emoji: "🛍️" },
          { word: "have a milkshake", alt: "had a milkshake", vn: "uống sữa lắc", emoji: "🥤" },
          { word: "eat pizza", alt: "ate pizza", vn: "ăn pizza", emoji: "🍕" },
        ],
        lesson_5: [
          "read a book",
          "write a poem",
          "do karate",
          "sing a song",
          "make a video",
          "build a tree house",
          "draw a picture",
        ],
      },
      grammar: {
        willWont: [
          { before: "Last weekend I", after: "a movie at the theater.", answer: "saw" },
          { before: "Kevin", after: "a new shirt at the store.", answer: "bought" },
          { before: "We", after: "pizza for lunch on Saturday.", answer: "ate" },
          { before: "I", after: "shopping with my mom and Sid.", answer: "went" },
          { before: "She", after: "a picture of her friends.", answer: "took" },
          { before: "They", after: "a milkshake after the movie.", answer: "had" },
          { before: "Suzy", after: "a tree house in the garden.", answer: "built" },
          { before: "I", after: "a video with my friends.", answer: "made" },
        ],
      },
      ai_speak: [
        "I saw a movie last weekend.",
        "I went shopping and I bought a new shirt.",
        "Did you buy anything? Yes, I did.",
        "What did you do last weekend? I did karate.",
        "Suzy built a tree house and I made a video.",
      ],
      reading: {
        text: "Movie Magic: A lot of movies today are animated. Animated movies can show talking animals or robots in space. In the past, animated movies were black and white. Artists drew the pictures with pencils and paper, and then a director made them into a movie. These days, animated movies are colorful. A person who makes them is called an animator. Animators use computers to draw 3D characters, and then they move the characters and give them voices. Making one movie can take many years! Some animators use small models instead. They move the models and take lots of pictures. Animated movies are amazing!",
        questions: [
          { q: "In the past, animated movies were black and white.", a: true },
          { q: "Today, animators use computers to make movies.", a: true },
          { q: "Making one animated movie takes only one day.", a: false },
        ],
      },
    },
    unit_3: {
      title: "Shareville Fair",
      icon: "🎡",
      formToggleLabel: "Past -ed ⏳",
      grammarGameMode: "COSMIC_BALLOON_POP",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "wave", alt: "waved", vn: "vẫy tay", emoji: "👋" },
          { word: "wait", alt: "waited", vn: "chờ / đợi", emoji: "⏳" },
          { word: "point", alt: "pointed", vn: "chỉ tay", emoji: "👉" },
          { word: "shout", alt: "shouted", vn: "hét / la lớn", emoji: "📢" },
          { word: "watch", alt: "watched", vn: "xem / theo dõi", emoji: "👀" },
          { word: "play", alt: "played", vn: "chơi", emoji: "🎯" },
          { word: "smile", alt: "smiled", vn: "mỉm cười", emoji: "😊" },
        ],
        lesson_5: ["juggle", "bounce", "laugh", "cry", "follow", "push", "pull", "carry"],
      },
      grammar: {
        willWont: [
          { before: "We", after: "in line for pizza.", answer: "waited" },
          { before: "Then we", after: "some fun games.", answer: "played" },
          { before: "Finally we", after: "some funny clowns.", answer: "watched" },
          { before: "The clowns", after: "at us.", answer: "waved" },
          { before: "Julie", after: "at the big Ferris wheel.", answer: "pointed" },
          { before: "Clara was happy. She", after: "at her friends.", answer: "smiled" },
          { before: "The children were excited. They", after: "and cheered.", answer: "shouted" },
        ],
      },
      ai_speak: [
        "How was the roller coaster? It was great!",
        "I waved at you and your mom.",
        "We waited in line for a long time.",
        "Did they juggle? Yes, they did.",
        "Did you like the clowns? No, I didn't.",
      ],
      reading: {
        text: "Cool Rides: Ferris wheels and roller coasters are fun rides at the fair. A man named George Ferris designed the very first Ferris wheel a long time ago, in 1893. It was 80 meters high, and it turned slowly in a big circle. Today there are Ferris wheels all around the world. The tallest one, the High Roller in Las Vegas, is 167 meters high! Roller coasters were slow in the past, but now they go very, very fast. Some of them are very tall, too. A lot of people feel scared on fast roller coasters, but they are also exciting. Which ride do you like best?",
        questions: [
          { q: "George Ferris designed the first Ferris wheel.", a: true },
          { q: "Roller coasters were very fast in the past.", a: false },
          { q: "The High Roller is in Las Vegas.", a: true },
        ],
      },
    },
    unit_2: {
      title: "At School",
      icon: "🏫",
      grammarGameMode: "ROCKET_BLASTER",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "social studies", vn: "môn Xã hội học", emoji: "🌍" },
          { word: "art", vn: "môn Mỹ thuật", emoji: "🎨" },
          { word: "English", vn: "môn Tiếng Anh", emoji: "📖" },
          { word: "music", vn: "môn Âm nhạc", emoji: "🎵" },
          { word: "math", vn: "môn Toán", emoji: "➗" },
          { word: "health", vn: "môn Sức khỏe", emoji: "🩺" },
          { word: "P.E.", vn: "môn Thể dục", emoji: "🏃" },
          { word: "science", vn: "môn Khoa học", emoji: "🔬" },
        ],
        lesson_5: ["gym", "cafeteria", "music room", "classroom", "art room", "computer lab"],
      },
      grammar: {
        willWont: [
          { before: "Do you have art today? Yes, I", after: ".", answer: "do" },
          { before: "Do you have P.E. today? No, I", after: ".", answer: "don't" },
          { before: "Does she have music today? Yes, she", after: ".", answer: "does" },
          { before: "Does he have math today? No, he", after: ".", answer: "doesn't" },
          { before: "Do they have English today? Yes, they", after: ".", answer: "do" },
          { before: "Does Suzy have science today? No, she", after: ".", answer: "doesn't" },
          { before: "Do we have health today? No, we", after: ".", answer: "don't" },
          { before: "Does Kevin have social studies? Yes, he", after: ".", answer: "does" },
        ],
      },
      ai_speak: [
        "Do you have P.E. today? Yes, I do.",
        "Does she have music today? No, she doesn't.",
        "Where's Sid? He's in the gym.",
        "What's he doing? He's playing basketball.",
        "I really like art, but I don't like math.",
      ],
      reading: {
        text: "A New Friend: Today there is a new student named Holly. 'Welcome to our class!' says the teacher. Holly asks, 'Do we have music today?' 'Yes, we do, but we have math first,' he answers. At lunchtime, Julie and Kevin sit with Holly and eat together. In art class, Holly paints a colorful picture. Later, the class has music, and Holly asks to play the drums. She plays really well! 'Wow, you're great, Holly!' her new friends say. Always be friendly to new people!",
        questions: [
          { q: "The children have math before music.", a: true },
          { q: "Holly eats lunch all alone.", a: false },
          { q: "Holly plays the drums very well.", a: true },
        ],
      },
    },
    unit_1: {
      title: "Good Morning",
      icon: "🌅",
      formToggleLabel: "He/She Form 👤",
      grammarGameMode: "ROCKET_BLASTER",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "wake up", alt: "wakes up", vn: "thức dậy", emoji: "⏰" },
          { word: "brush my hair", alt: "brushes hair", vn: "chải tóc", emoji: "💇" },
          { word: "take a shower", alt: "takes a shower", vn: "tắm vòi sen", emoji: "🚿" },
          { word: "get dressed", alt: "gets dressed", vn: "mặc quần áo", emoji: "👕" },
          { word: "wash my face", alt: "washes face", vn: "rửa mặt", emoji: "🧼" },
          { word: "have breakfast", alt: "has breakfast", vn: "ăn sáng", emoji: "🥣" },
          { word: "make breakfast", alt: "makes breakfast", vn: "chuẩn bị bữa sáng", emoji: "🍳" },
          { word: "go to school", alt: "goes to school", vn: "đi học", emoji: "🏫" },
        ],
        lesson_5: ["take a taxi", "take the bus", "take the train", "take the subway", "walk", "ride a bicycle"],
      },
      grammar: {
        willWont: [
          { before: "Every morning I", after: "wash my face.", answer: "always" },
          { before: "He hates breakfast. He", after: "has breakfast.", answer: "never" },
          { before: "On most days, she", after: "takes a shower.", answer: "usually" },
          { before: "Once a week, we", after: "take the bus.", answer: "sometimes" },
          { before: "I wake up at six every single day. I", after: "wake up late.", answer: "never" },
          { before: "My dad", after: "makes breakfast on most mornings.", answer: "usually" },
          { before: "Every single day, I", after: "brush my hair.", answer: "always" },
          { before: "Once or twice a month, we", after: "ride a bicycle to school.", answer: "sometimes" },
        ],
      },
      ai_speak: [
        "I always wake up at six o'clock.",
        "She usually makes breakfast for the family.",
        "How often do you ride your bicycle to school?",
        "He never has breakfast before school.",
        "I sometimes take the bus, but I usually walk.",
      ],
      reading: {
        text: "Matt's Busy Morning: Matt usually wakes up at seven o'clock, but today he wakes up late! He quickly washes his face, brushes his teeth, gets dressed, and brushes his hair. Matt's dad usually makes breakfast for the family. Soon his friend Sid is at the door, but Matt is still not ready for school. 'Look in the mirror, Matt!' says his mom. Oh no! Matt forgot to finish getting ready. Always be prepared for school!",
        questions: [
          { q: "Matt usually wakes up at seven o'clock.", a: true },
          { q: "Matt takes a long shower every morning.", a: false },
          { q: "Matt is not ready when his friend Sid arrives.", a: true },
        ],
      },
    },
  },
  level_5: {
    unit_1: {
      title: "Adventure Camp",
      icon: "🪐",
      formToggleLabel: "Past Form ⏳",
      grammarGameMode: "ASTEROID_SMASHER",
      quizGameMode: "FOUR_IN_A_ROW",
      vocabulary: {
        lesson_1: [
          { word: "build a shelter", alt: "built a shelter", vn: "dựng lều trú ẩn", emoji: "⛺" },
          { word: "ride a zipline", alt: "rode a zipline", vn: "trượt đu dây tự do", emoji: "⚡" },
          { word: "sleep in a tent", alt: "slept in a tent", vn: "ngủ trong lều", emoji: "⛺" },
          { word: "go hiking", alt: "went hiking", vn: "đi bộ đường dài", emoji: "🥾" },
          { word: "go mountain biking", alt: "went mountain biking", vn: "đi xe đạp địa hình", emoji: "🚲" },
          { word: "cook on a campfire", alt: "cooked on a campfire", vn: "nấu ăn bên lửa trại", emoji: "🔥" },
          { word: "go horseback riding", alt: "went horseback riding", vn: "cưỡi ngựa", emoji: "🐎" },
          { word: "go canoeing", alt: "went canoeing", vn: "chèo thuyền canoe", emoji: "🛶" },
        ],
        lesson_5: [
          "jump on a trampoline",
          "go climbing",
          "play volleyball",
          "make jewelry",
          "play table tennis",
          "play badminton",
          "go ice skating",
          "go bowling",
        ],
      },
      ai_speak: [
        "I cooked dinner on a campfire last night.",
        "I built a shelter and I slept in it.",
        "This morning we went hiking and I rode on a zipline.",
        "Did you go horseback riding yesterday afternoon?",
        "We didn't go canoeing because it started raining.",
      ],
      reading: {
        text: "Camp Energy Journal: Yesterday was amazing. We built a shelter in the woods. Later, we cooked on a campfire...",
        questions: [
          { q: "They built a shelter yesterday.", a: true },
          { q: "They cooked inside a kitchen.", a: false },
          { q: "They slept in a hotel.", a: false },
        ],
      },
    },
    unit_2: {
      title: "Gadget Nebula",
      icon: "🌀",
      formToggleLabel: "Plural Form 👥",
      grammarGameMode: "ROCKET_FUEL",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "smartwatch", alt: "smartwatches", vn: "đồng hồ thông minh", emoji: "⌚" },
          { word: "laptop", alt: "laptops", vn: "máy tính xách tay", emoji: "💻" },
          { word: "smartphone", alt: "smartphones", vn: "điện thoại thông minh", emoji: "📱" },
          { word: "tablet", alt: "tablets", vn: "máy tính bảng", emoji: "📟" },
          { word: "digital camera", alt: "digital cameras", vn: "máy ảnh kỹ thuật số", emoji: "📷" },
          { word: "e-reader", alt: "e-readers", vn: "máy đọc sách", emoji: "📖" },
          { word: "headphones", vn: "tai nghe", emoji: "🎧" },
          { word: "portable speaker", alt: "portable speakers", vn: "loa di động", emoji: "🔊" },
        ],
        lesson_5: [
          "upload a photo",
          "text a friend",
          "stream a video",
          "download a song",
          "charge a phone",
          "log in",
          "print a document",
          "search the internet",
        ],
      },
      ai_speak: [
        "At nine o'clock last night, I was streaming a video.",
        "He was texting a friend when the Wi-Fi stopped.",
        "They were listening to music during class.",
        "What were you downloading when your laptop died?",
        "She was charging her smartphone while talking to me.",
      ],
      reading: {
        text: "Vlogging Kit & Tech Tools Review: This smartwatch is excellent for tracking steps. The portable speaker is loud...",
        questions: [
          { q: "The smartwatch tracks steps.", a: true },
          { q: "The speaker is very quiet.", a: false },
          { q: "The review talks about cooking.", a: false },
        ],
      },
    },
    unit_3: {
      title: "Surprise!",
      icon: "☄️",
      formToggleLabel: "Past Form ⏳",
      grammarGameMode: "NEBULA_BRIDGE",
      quizGameMode: "SPACE_DEFENSE_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "buy groceries", alt: "bought groceries", vn: "mua nhu yếu phẩm", emoji: "🛒" },
          { word: "walk the dog", alt: "walked the dog", vn: "dắt chó đi dạo", emoji: "🦮" },
          { word: "study for a test", alt: "studied for a test", vn: "ôn thi", emoji: "📝" },
          { word: "take out the trash", alt: "took out the trash", vn: "đổ rác", emoji: "🗑️" },
          { word: "buy a present", alt: "bought a present", vn: "mua quà", emoji: "🎁" },
          { word: "play chess", alt: "played chess", vn: "chơi cờ vua", emoji: "♟️" },
          { word: "read the newspaper", alt: "read the newspaper", vn: "đọc báo giấy", emoji: "📰" },
          { word: "watch the news", alt: "watched the news", vn: "xem thời sự", emoji: "📺" },
        ],
        lesson_5: [
          "go online",
          "listen to the radio",
          "read a magazine",
          "download an app",
          "look at the screen",
          "read a blog post",
        ],
      },
      ai_speak: [
        "A man was walking his dog when it ran into the street.",
        "What were you doing when the bell rang this morning?",
        "Dad and Seb were buying groceries when the accident happened.",
        "She was studying for a test when her friend called her.",
        "They were playing chess when they heard a loud noise outside.",
      ],
      reading: {
        text: "The History of News: Long ago, there were no radios, televisions, or smartphones. People got their daily updates from a town crier in the busy town square. The crier would ring a heavy bell and shout important announcements to everyone around the world. Later, printing presses were invented, and people started reading the newspaper to discover what was happening.",
        questions: [
          { q: "People used smartphones to read news long ago.", a: false },
          { q: "A town crier would ring a bell in the town square.", a: true },
          { q: "The story discusses the history of how people get news.", a: true },
        ],
      },
    },
    unit_4: {
      title: "Myths & Legends",
      icon: "🧜‍♀️",
      formToggleLabel: "Plural Form 👥",
      grammarGameMode: "ORBITAL_ALIGNMENT",
      quizGameMode: "QUANTUM_MEMORY_MATCH",
      vocabulary: {
        lesson_1: [
          { word: "minotaur", alt: "minotaurs", vn: "quái vật nhân ngưu", emoji: "🐂" },
          { word: "mermaid", alt: "mermaids", vn: "nàng tiên cá", emoji: "🧜‍♀️" },
          { word: "phoenix", alt: "phoenixes", vn: "chim phượng hoàng", emoji: "🦅" },
          { word: "dragon", alt: "dragons", vn: "con rồng", emoji: "🐉" },
          { word: "centaur", alt: "centaurs", vn: "nhân mã", emoji: "🏹" },
          { word: "unicorn", alt: "unicorns", vn: "kỳ lân", emoji: "🦄" },
          { word: "pegasus", alt: "pegasuses", vn: "ngựa có cánh pegasus", emoji: "🐎" },
          { word: "kraken", alt: "krakens", vn: "quái vật mực khổng lồ", emoji: "🦑" },
        ],
        lesson_5: ["tell a story", "paint a picture", "write a poem", "sing a song", "read a comic", "make a statue"],
      },
      ai_speak: [
        "A minotaur was a monster that lived in a giant labyrinth.",
        "Mermaids were mythical creatures who lived deep in the ocean.",
        "The phoenix is a magical bird that can be reborn from fire.",
        "Dragons are powerful creatures that breathe fire and guard gold.",
        "The centaur was a legendary warrior who was half man and half horse.",
      ],
      reading: {
        text: "The Legend of Atlantis: Long ago, Greek philosophers wrote stories about a magnificent, powerful island nation called Atlantis. This utopian city possessed incredible technology, golden temples, and vast wealth. However, the legends claim that the people became greedy, angering the ancient gods. In a single day and night of misfortune, the entire island was swallowed by the sea, disappearing forever into the dark Atlantic ocean.",
        questions: [
          { q: "Atlantis was a real city that scientists found yesterday.", a: false },
          { q: "Legends say the island was swallowed by the sea.", a: true },
          { q: "The story discusses a famous myth about a sunken island.", a: true },
        ],
      },
    },
    unit_5: {
      title: "Let's Cook!",
      icon: "🍳",
      formToggleLabel: "Plural Form 👥",
      grammarGameMode: "QUANTUM_SCALE",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "flour", vn: "bột mì", emoji: "🌾" },
          { word: "butter", vn: "bơ", emoji: "🧈" },
          { word: "sugar", vn: "đường", emoji: "🍬" },
          { word: "jelly", vn: "thạch", emoji: "🍮" },
          { word: "salt and pepper", vn: "muối và hạt tiêu", emoji: "🧂" },
          { word: "honey", vn: "mật ong", emoji: "🍯" },
          { word: "olive", alt: "olives", vn: "quả ô-liu", emoji: "🫒" },
          { word: "strawberry", alt: "strawberries", vn: "quả dâu tây", emoji: "🍓" },
          { word: "mushroom", alt: "mushrooms", vn: "cây nấm", emoji: "🍄" },
        ],
        lesson_5: ["cup", "teaspoon", "tablespoon", "knife", "bowl", "fork", "plate", "glass"],
      },
      ai_speak: [
        "There is too much sugar in this giant bowl.",
        "There aren't enough strawberries to make the jelly.",
        "Could you hand me a tablespoon and a clean knife?",
        "There are too many olives on that small plate.",
        "Is there enough flour and butter to bake the cake?",
      ],
      reading: {
        text: "The Galaxy Bakery: Today, Seb and Taylor are in the spaceship kitchen. They want to bake a special strawberry surprise cake for Mom's birthday. There is enough flour and butter, but there isn't enough sugar in the cabinet. Seb looks around and says, 'We have too many mushrooms and olives, but we need more sweet ingredients!' Luckily, Taylor finds a jar of golden honey. They use a measuring cup and a tablespoon to mix everything in a massive bowl. Mom will love it!",
        questions: [
          { q: "They are making a birthday cake for Mom.", a: true },
          { q: "They have too much sugar in the kitchen.", a: false },
          { q: "They use a cup and a tablespoon to mix the ingredients.", a: true },
        ],
      },
    },
    unit_6: {
      title: "Save Our Planet!",
      icon: "🌍",
      formToggleLabel: "Plural Form 👥",
      grammarGameMode: "ECO_BALANCER",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "giant panda", alt: "giant pandas", vn: "gấu trúc lớn", emoji: "🐼" },
          { word: "black rhino", alt: "black rhinos", vn: "tê giác đen", emoji: "🦏" },
          { word: "blue whale", alt: "blue whales", vn: "cá voi xanh", emoji: "🐋" },
          { word: "mountain gorilla", alt: "mountain gorillas", vn: "khỉ đột núi", emoji: "🦍" },
          { word: "snow leopard", alt: "snow leopards", vn: "báo tuyết", emoji: "🐆" },
          { word: "sea turtle", alt: "sea turtles", vn: "rùa biển", emoji: "🐢" },
          { word: "polar bear", alt: "polar bears", vn: "gấu bắc cực", emoji: "🐻‍❄️" },
          { word: "orangutan", alt: "orangutans", vn: "đười ươi", emoji: "🦧" },
        ],
        lesson_5: [
          "recycle trash",
          "plant trees",
          "save water",
          "turn off lights",
          "clean up parks",
          "reuse plastic bags",
        ],
      },
      ai_speak: [
        "If we don't protect the giant pandas, they will disappear.",
        "We should turn off the lights to save energy every day.",
        "If people plant more green trees, the air will be cleaner.",
        "Sea turtles are endangered because there is too much plastic in the ocean.",
        "What will happen if we recycle all our plastic bottles?",
      ],
      reading: {
        text: "The Green Mission: Our planet is home to many incredible creatures like the giant panda and the blue whale. However, pollution and climate change are putting their ecosystems in danger. If we don't take action now, these beautiful animals might disappear forever. Luckily, children around the world are helping. By recycling paper, planting green trees, and saving clean water, every small explorer can make a massive difference to protect Mother Earth.",
        questions: [
          { q: "Pollution can put animal ecosystems in danger.", a: true },
          { q: "Only adults can help protect the planet.", a: false },
          { q: "The story advises us to recycle paper and plant trees.", a: true },
        ],
      },
    },
    unit_7: {
      title: "High-Tech Future",
      icon: "🤖",
      formToggleLabel: "Plural Form 👥",
      grammarGameMode: "FUTURE_WILL_WONT",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "flying car", alt: "flying cars", vn: "xe bay", emoji: "🚗" },
          { word: "robot worker", alt: "robot workers", vn: "người máy giúp việc", emoji: "🤖" },
          { word: "3D printer", alt: "3D printers", vn: "máy in 3D", emoji: "🖨️" },
          { word: "drone", alt: "drones", vn: "máy bay không người lái", emoji: "🚁" },
          { word: "hoverboard", alt: "hoverboards", vn: "ván trượt bay", emoji: "🛹" },
          { word: "VR headset", alt: "VR headsets", vn: "kính thực tế ảo", emoji: "🥽" },
          { word: "jetpack", alt: "jetpacks", vn: "ba lô phản lực bay", emoji: "🚀" },
          { word: "electric bike", alt: "electric bikes", vn: "xe đạp điện", emoji: "🚲" },
        ],
        lesson_5: [
          "skyscrapers",
          "green buildings",
          "energy",
          "automatic",
          "smart homes",
          "driverless cars",
          "inventions",
          "travel",
        ],
      },
      grammar: {
        willWont: [
          { before: "We", after: "drive flying cars.", answer: "will" },
          { before: "We", after: "go to work.", answer: "won't" },
          { before: "Robot workers", after: "do all the work.", answer: "will" },
          { before: "Drones", after: "deliver pizza to people's homes.", answer: "will" },
          { before: "We", after: "wear VR headsets when we play computer games.", answer: "will" },
          { before: "I", after: "ride an electric bike to school.", answer: "will" },
          { before: "I", after: "take the bus.", answer: "won't" },
          { before: "We", after: "have to do any chores.", answer: "won't" },
        ],
      },
      ai_speak: [
        "In the future, I'll ride a hoverboard to school.",
        "I won't ride a hoverboard because they are scary.",
        "Robot workers will do everything for us!",
        "Will we live in houses in the future?",
        "We'll travel with jetpacks and also with flying cars.",
      ],
      reading: {
        text: "Life in the Future: Life will be very different in 50 years. There will be more people on Earth, so we'll live and work in tall skyscrapers. The skyscrapers will be green buildings with trees and plants everywhere. We'll live in smart homes, so everything will be automatic. Our robot workers will clean our houses, feed our pets, and cook breakfast for us. We won't have to do any chores! Transportation will be different, too. There will be driverless cars, so we won't need to drive. With new inventions like flying cars and jetpacks, people will travel much faster than they do today. Life in the future will be different, and it will be easier!",
        questions: [
          { q: "In the future, people will live in tall skyscrapers.", a: true },
          { q: "People will have to do all their chores themselves.", a: false },
          { q: "There will be driverless cars, so we won't need to drive.", a: true },
        ],
      },
    },
    unit_8: {
      title: "On Vacation!",
      icon: "🛳️",
      formToggleLabel: "Past Form ⏳",
      grammarGameMode: "NEBULA_GATEWAY",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "go on a cruise", alt: "went on a cruise", vn: "đi du thuyền", emoji: "🛳️" },
          { word: "visit a theme park", alt: "visited a theme park", vn: "thăm công viên giải trí", emoji: "🎢" },
          { word: "see a show", alt: "saw a show", vn: "xem biểu diễn", emoji: "🎭" },
          { word: "go to the beach", alt: "went to the beach", vn: "đi bãi biển", emoji: "🏖️" },
          { word: "stay in a hotel", alt: "stayed in a hotel", vn: "ở khách sạn", emoji: "🏨" },
          { word: "visit a museum", alt: "visited a museum", vn: "thăm bảo tàng", emoji: "🏛️" },
          { word: "go sightseeing", alt: "went sightseeing", vn: "đi ngắm cảnh", emoji: "🏙️" },
          { word: "buy souvenirs", alt: "bought souvenirs", vn: "mua quà lưu niệm", emoji: "🎁" },
        ],
        lesson_5: [
          "pack a suitcase",
          "book a flight",
          "buy a ticket",
          "check in",
          "board the plane",
          "explore the city",
        ],
      },
      ai_speak: [
        "Have you ever stayed in a luxury hotel near the beach?",
        "We have already bought beautiful souvenirs for our family.",
        "She hasn't visited the space theme park yet.",
        "They went sightseeing and saw an incredible light show last night.",
        "He is going to pack his big suitcase for the cruise tomorrow.",
      ],
      reading: {
        text: "The Galactic Vacation: Summer vacation has finally arrived! This year, Leo's family is planning an incredible trip across the solar system. First, they booked a flight on a hyper-drive starship. Yesterday, they checked in at the spaceport terminal and boarded the plane. They are going to stay in a floating hotel near the cosmic beach. Leo wants to visit a famous space museum and buy alien souvenirs for his best friends back home. It will be an unforgettable adventure!",
        questions: [
          { q: "Leo's family is going on a vacation across the solar system.", a: true },
          { q: "They forgot to book a flight and stayed home.", a: false },
          { q: "Leo wants to buy souvenirs for his friends.", a: true },
        ],
      },
    },
  },
  level_3: {
    unit_2: {
      title: "Healthy Food",
      icon: "🥗",
      formToggleLabel: "Plural ⬆️",
      grammarGameMode: "ROCKET_BLASTER",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "mango", alt: "mangoes", vn: "xoài", emoji: "🥭" },
          { word: "potato", alt: "potatoes", vn: "khoai tây", emoji: "🥔" },
          { word: "peach", alt: "peaches", vn: "quả đào", emoji: "🍑" },
          { word: "carrot", alt: "carrots", vn: "cà rốt", emoji: "🥕" },
          { word: "tomato", alt: "tomatoes", vn: "cà chua", emoji: "🍅" },
          { word: "cucumber", alt: "cucumbers", vn: "dưa leo / dưa chuột", emoji: "🥒" },
          { word: "avocado", alt: "avocados", vn: "quả bơ", emoji: "🥑" },
        ],
        lesson_5: ["pasta", "popcorn", "tea", "coffee", "soda", "beef", "chicken", "lemonade"],
      },
      grammar: {
        willWont: [
          { before: "There are", after: "carrots in the box.", answer: "some" },
          { before: "There aren't", after: "tomatoes today.", answer: "any" },
          { before: "There", after: "some soda in the fridge.", answer: "is" },
          { before: "There are some avocados, but there", after: "any apples.", answer: "aren't" },
          { before: "Is there any popcorn? No, there", after: ".", answer: "isn't" },
          { before: "Are there any peaches? Yes, there", after: ".", answer: "are" },
        ],
      },
      ai_speak: [
        "There are some avocados, but there aren't any apples.",
        "Are there any apples? No, there aren't.",
        "Is there any popcorn? No, there isn't.",
        "There's some soda. Is there any coffee?",
        "Are there any peaches? Yes, there are.",
      ],
      reading: {
        text: "Food Groups: There are four food groups. They are healthy and good for our bodies. Peaches, carrots, cucumbers, and potatoes are in the fruit and vegetable group. Bread, rice, and pasta are in the grain group. Fish, meat, beans, and eggs are in the protein group. Yogurt, cheese, and milk are in the dairy group. Candy and soda are not in any food group because they aren't healthy foods. Try to eat food from all four groups every day!",
        questions: [
          { q: "There are four food groups.", a: true },
          { q: "Candy and soda are healthy foods.", a: false },
          { q: "Yogurt and cheese are in the dairy group.", a: true },
        ],
      },
    },
    unit_8: {
      title: "Camping",
      icon: "🏕️",
      grammarGameMode: "ROCKET_BLASTER",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "mountain", vn: "núi / ngọn núi", emoji: "⛰️" },
          { word: "cloud", vn: "đám mây", emoji: "☁️" },
          { word: "star", vn: "ngôi sao", emoji: "⭐" },
          { word: "cave", vn: "hang động", emoji: "🕳️" },
          { word: "bat", vn: "con dơi", emoji: "🦇" },
          { word: "river", vn: "dòng sông / con sông", emoji: "🏞️" },
          { word: "field", vn: "cánh đồng", emoji: "🌾" },
          { word: "road", vn: "con đường", emoji: "🛣️" },
        ],
        lesson_5: [
          "up the mountain",
          "down the mountain",
          "into the cave",
          "out of the cave",
          "around the lake",
          "across the river",
          "along the road",
        ],
      },
      grammar: {
        willWont: [
          { before: "We climbed to the top. We went", after: "the mountain.", answer: "up" },
          { before: "We walked back to the bottom. We went", after: "the mountain.", answer: "down" },
          { before: "We explored the dark cave. We went", after: "the cave.", answer: "into" },
          { before: "We left the dark cave. We went", after: "of the cave.", answer: "out" },
          { before: "We walked from one side to the other. We went", after: "the river.", answer: "across" },
          { before: "We walked beside the water. We went", after: "the river.", answer: "along" },
          { before: "We walked in a big circle. We went", after: "the lake.", answer: "around" },
        ],
      },
      ai_speak: [
        "Where did you go? We went to the river.",
        "We went into the cave. There were some bats!",
        "Was there a road by the river? No, there wasn't.",
        "Were there any stars last night? Yes, there were!",
        "We didn't go up the mountain. We went across the field.",
      ],
      reading: {
        text: "A Camping Trip: Last weekend, Kevin and his dad went camping near a big mountain. There was a clean river, and there were many tall trees. At night, the sky was beautiful. There were lots of stars and a few clouds. The next morning, they walked up the mountain and into a dark cave. There were some bats inside, so they ran out quickly! It was a fun and exciting trip.",
        questions: [
          { q: "Kevin and his dad went camping near a mountain.", a: true },
          { q: "There were no stars in the night sky.", a: false },
          { q: "They saw some bats in the cave.", a: true },
        ],
      },
    },
    unit_7: {
      title: "Yesterday",
      icon: "🕗",
      grammarGameMode: "ROCKET_BLASTER",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "school", vn: "trường học", emoji: "🏫" },
          { word: "beach", vn: "bãi biển", emoji: "🏖️" },
          { word: "home", vn: "nhà / ở nhà", emoji: "🏠" },
          { word: "doctor's office", vn: "phòng khám bác sĩ", emoji: "🩺" },
          { word: "sports center", vn: "trung tâm thể thao", emoji: "🏟️" },
          { word: "Grandma's house", vn: "nhà bà", emoji: "👵" },
          { word: "park", vn: "công viên", emoji: "🏞️" },
        ],
        lesson_5: ["sick", "scared", "tired", "angry", "surprised", "happy", "excited"],
      },
      grammar: {
        willWont: [
          { before: "Matt built a sandcastle. He was at the", after: ".", answer: "beach" },
          { before: "Julie was sick. She was at the", after: ".", answer: "doctor's office" },
          { before: "We played basketball. We were at the", after: ".", answer: "sports center" },
          { before: "Clara ate cookies. She was at", after: ".", answer: "Grandma's house" },
          { before: "I did my homework. I was at", after: ".", answer: "home" },
          { before: "On Monday the children were at", after: ".", answer: "school" },
          { before: "We rode our bikes. We were at the", after: ".", answer: "park" },
        ],
      },
      ai_speak: [
        "Where were you yesterday? I was at the beach.",
        "Matt wasn't at school. He was at the sports center.",
        "Was she happy? No, she wasn't. She was tired.",
        "Were they surprised? Yes, they were!",
        "I was at Grandma's house. I was excited and happy.",
      ],
      reading: {
        text: "Where Were You Yesterday? Yesterday was Saturday, so the children were not at school. Matt was at the beach. He was happy because he loves the sea. Julie was at home. She was a little tired, so she played quiet computer games. Clara was at her grandma's house. She was excited because Grandma made cookies! In the evening, everyone was at home again. It was a fun day for the whole class.",
        questions: [
          { q: "Yesterday the children were at school.", a: false },
          { q: "Matt was happy at the beach.", a: true },
          { q: "Clara was at her grandma's house.", a: true },
        ],
      },
    },
    unit_6: {
      title: "Jobs and Places",
      icon: "💼",
      grammarGameMode: "ROCKET_BLASTER",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "construction worker", vn: "công nhân xây dựng", emoji: "👷" },
          { word: "librarian", vn: "thủ thư", emoji: "📚" },
          { word: "paramedic", vn: "nhân viên cấp cứu", emoji: "🚑" },
          { word: "architect", vn: "kiến trúc sư", emoji: "📐" },
          { word: "fisherman", vn: "ngư dân", emoji: "🎣" },
          { word: "dancer", vn: "vũ công / diễn viên múa", emoji: "💃" },
          { word: "writer", vn: "nhà văn", emoji: "✍️" },
          { word: "musician", vn: "nhạc sĩ / nhạc công", emoji: "🎸" },
        ],
        lesson_5: ["office", "hospital", "school", "factory", "farm", "restaurant", "boat"],
      },
      grammar: {
        willWont: [
          { before: "Kevin loves books. He wants to be a", after: ".", answer: "librarian" },
          { before: "Julie loves music. She wants to be a", after: ".", answer: "musician" },
          { before: "Matt designs buildings. He wants to be an", after: ".", answer: "architect" },
          { before: "Clara loves to dance. She wants to be a", after: ".", answer: "dancer" },
          { before: "I write stories. I want to be a", after: ".", answer: "writer" },
          { before: "She helps sick people. She wants to be a", after: ".", answer: "paramedic" },
          { before: "He catches fish at sea. He wants to be a", after: ".", answer: "fisherman" },
          { before: "I build houses. I want to be a", after: ".", answer: "construction worker" },
        ],
      },
      ai_speak: [
        "What do you want to be? I want to be an architect.",
        "I don't want to be a writer. I want to be a musician.",
        "Where does she work? She works in a hospital.",
        "He works on a boat. He is a fisherman.",
        "A teacher works in a school, and a cook works in a restaurant.",
      ],
      reading: {
        text: "The Flying Doctors: Most people with service jobs work in an office or a hospital. In Australia, some doctors are different. There are many small towns and farms far away, and most of these places do not have a hospital nearby. When people there need help, they call the Flying Doctors. These doctors do not work in one building — they fly airplanes to reach their patients! Doctors, nurses, and even dentists travel by plane to help people in faraway places. They have important and exciting jobs.",
        questions: [
          { q: "The Flying Doctors travel by airplane to help people.", a: true },
          { q: "Every small town in Australia has a big hospital.", a: false },
          { q: "Doctors, nurses, and dentists can all be Flying Doctors.", a: true },
        ],
      },
    },
    unit_1: {
      title: "Family",
      icon: "👪",
      grammarGameMode: "ROCKET_BLASTER",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "parents", vn: "bố mẹ / cha mẹ", emoji: "👫" },
          { word: "uncle", vn: "chú / bác / cậu", emoji: "👨" },
          { word: "aunt", vn: "cô / dì / bác gái", emoji: "👩" },
          { word: "cousin", vn: "anh / chị / em họ", emoji: "🧒" },
          { word: "big brother", vn: "anh trai", emoji: "👦" },
          { word: "grandparents", vn: "ông bà", emoji: "👴" },
          { word: "little sister", vn: "em gái", emoji: "👧" },
        ],
        lesson_5: ["glasses", "keys", "cell phone", "sandals", "e-reader", "wallet", "comic book"],
      },
      grammar: {
        willWont: [
          { before: "Whose glasses are these? They're", after: ".", answer: "mine" },
          { before: "Whose cell phone is this? It's", after: ".", answer: "hers" },
          { before: "Whose keys are these? They're", after: ".", answer: "his" },
          { before: "Whose wallet is this? It's", after: ".", answer: "yours" },
          { before: "Whose sandals are these? They're", after: ".", answer: "ours" },
          { before: "Whose comic book is this? It's", after: ".", answer: "theirs" },
        ],
      },
      ai_speak: [
        "Who's he? He's my cousin.",
        "Who are they? They're my aunt and uncle.",
        "This is my family. I love my parents and my little sister.",
        "Whose cell phone is this? It's hers.",
        "These are my grandparents. They live with us.",
      ],
      reading: {
        text: "Different Families: All families are different. Oliver has a small family. They live in the city. The city is very busy, with many people and cars. Oliver's family likes going shopping and going to the movies. Josie has a big family. They live in the countryside, where there are a lot of plants and animals. Her family enjoys nature. They like swimming in the river and flying kites together. Jenny's family also lives in the countryside. She has a small family. They like catching butterflies and growing vegetables. All families are different, and your family is different, too!",
        questions: [
          { q: "Oliver's family lives in the city.", a: true },
          { q: "Josie has a small family.", a: false },
          { q: "Jenny's family likes growing vegetables.", a: true },
        ],
      },
    },

    unit_3: {
      title: "The Weather",
      icon: "🌦️",
      formToggleLabel: "Comparative -er ⬆️",
      grammarGameMode: "ROCKET_BLASTER",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "rainy", alt: "rainier", vn: "có mưa / mưa nhiều", emoji: "🌧️" },
          { word: "windy", alt: "windier", vn: "có gió / nhiều gió", emoji: "💨" },
          { word: "hot", alt: "hotter", vn: "nóng", emoji: "🥵" },
          { word: "sunny", alt: "sunnier", vn: "có nắng / nắng đẹp", emoji: "☀️" },
          { word: "snowy", alt: "snowier", vn: "có tuyết", emoji: "❄️" },
          { word: "cold", alt: "colder", vn: "lạnh", emoji: "🥶" },
          { word: "cloudy", alt: "cloudier", vn: "nhiều mây / âm u", emoji: "☁️" },
        ],
        lesson_5: ["roller skate", "ice skate", "surf", "dive", "ski", "hike", "fish"],
      },
      grammar: {
        willWont: [
          { before: "Look! It's raining. It's", after: "today.", answer: "rainy" },
          { before: "The sun is shining. It's", after: "today.", answer: "sunny" },
          { before: "The wind is very strong. It's", after: ".", answer: "windy" },
          { before: "There is snow everywhere. It's", after: ".", answer: "snowy" },
          { before: "The sky is grey with clouds. It's", after: ".", answer: "cloudy" },
          { before: "Brrr! I need my coat. It's", after: ".", answer: "cold" },
          { before: "I want some water. It's very", after: "today.", answer: "hot" },
        ],
      },
      ai_speak: [
        "What's the weather like today? It's sunny and hot.",
        "It's rainy and windy. Let's stay inside.",
        "It's cold and snowy. I want to ski!",
        "What are you doing? I'm roller skating in the park.",
        "It's cloudy today. We're fishing by the lake.",
      ],
      reading: {
        text: "Storms: Storms can happen in different kinds of weather. Thunderstorms happen in warm or hot weather. In a thunderstorm there is rain, lightning, and thunder. We can see the lightning, but we can only hear the thunder. Sometimes a storm is very windy, and sometimes it is very rainy. A lot of rain can make a flood. Hurricanes also happen in warm weather, and they start in the ocean. Inside a hurricane it is very windy, and the wind can damage trees, cars, and houses. Tornadoes start in thunderstorms. The wind in a tornado goes around and around. It can pick up animals, a car, or even a house. Watch out for storms and be careful!",
        questions: [
          { q: "Thunderstorms happen in warm or hot weather.", a: true },
          { q: "We can see thunder.", a: false },
          { q: "A tornado can pick up a car.", a: true },
        ],
      },
    },
    unit_4: {
      title: "After School",
      icon: "⏰",
      formToggleLabel: "He/She Form 👤",
      grammarGameMode: "COSMIC_BALLOON_POP",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "do homework", alt: "does homework", vn: "làm bài tập về nhà", emoji: "📝" },
          { word: "practice the piano", alt: "practices the piano", vn: "luyện đàn piano", emoji: "🎹" },
          { word: "go to English class", alt: "goes to English class", vn: "đi học lớp tiếng Anh", emoji: "🇬🇧" },
          { word: "have a snack", alt: "has a snack", vn: "ăn nhẹ / ăn vặt", emoji: "🍪" },
          { word: "watch a video", alt: "watches a video", vn: "xem video", emoji: "📺" },
          { word: "go to gymnastics", alt: "goes to gymnastics", vn: "đi tập thể dục dụng cụ", emoji: "🤸" },
          { word: "wash the dishes", alt: "washes the dishes", vn: "rửa chén bát", emoji: "🧽" },
          { word: "play video games", alt: "plays video games", vn: "chơi trò chơi điện tử", emoji: "🎮" },
        ],
        lesson_5: [
          "take art classes",
          "play soccer",
          "go to ballet class",
          "do karate",
          "play the violin",
          "sing in the choir",
        ],
      },
      ai_speak: [
        "What do you do after school? I do my homework.",
        "He goes to English class and he doesn't wash the dishes.",
        "Does she practice the piano or play video games?",
        "What does he do after school? He goes to gymnastics.",
        "Do you take art classes or do karate after school?",
      ],
      reading: {
        text: "After-School Fun: Every day after school, the children on the Space Station have lots of fun. Toby does his homework first, and then he plays cosmic video games. Ellen practices the piano with her music robot buddy. In the afternoon, some cosmic campers go to English class or gymnastics. What do you do after school?",
        questions: [
          { q: "Toby plays video games before doing his homework.", a: false },
          { q: "Ellen practices the piano with a robot.", a: true },
          { q: "Some campers go to English class after school.", a: true },
        ],
      },
    },
    unit_5: {
      title: "Let's Play!",
      icon: "⚽",
      formToggleLabel: "-ing Form 🔄",
      grammarGameMode: "COSMIC_BALLOON_POP",
      quizGameMode: "ALIEN_TRIVIA",
      vocabulary: {
        lesson_1: [
          { word: "play basketball", alt: "playing basketball", vn: "chơi bóng rổ", emoji: "🏀" },
          { word: "play soccer", alt: "playing soccer", vn: "chơi bóng đá", emoji: "⚽" },
          { word: "go swimming", alt: "going swimming", vn: "đi bơi", emoji: "🏊" },
          { word: "ride a bike", alt: "riding a bike", vn: "đi xe đạp", emoji: "🚲" },
          { word: "inline skate", alt: "inline skating", vn: "trượt patin", emoji: "🛼" },
          { word: "skateboard", alt: "skateboarding", vn: "trượt ván", emoji: "🛹" },
          { word: "play tennis", alt: "playing tennis", vn: "chơi quần vợt", emoji: "🎾" },
          { word: "dance", alt: "dancing", vn: "nhảy múa", emoji: "💃" },
        ],
        lesson_5: ["play the guitar", "sing songs", "draw pictures", "cook dinner", "read books", "watch cartoons"],
      },
      ai_speak: [
        "He is playing basketball with his friends in the park.",
        "She is going swimming because the weather is very hot.",
        "Are you riding a bike or inline skating right now?",
        "My brother loves skateboarding but he cannot play tennis.",
        "We are dancing and singing happy songs together today.",
      ],
      reading: {
        text: "The Galactic Sports Day: Today is the annual Sports Day on the Space Station. All the alien children are excited. Toby is playing basketball with his floating drone buddy. Luna is going swimming in the zero-gravity pool. Some cosmic campers are riding bikes, and others are inline skating down the neon hallways.",
        questions: [
          { q: "Today is the annual Sports Day on the Space Station.", a: true },
          { q: "Luna is playing tennis in the kitchen.", a: false },
          { q: "The children are riding bikes and inline skating.", a: true },
        ],
      },
    },
  },
};
export function getUnitData(unit: any, level: string = "level_5"): any {
  const lvl = CURRICULUM_DATA[level];
  if (lvl && lvl[`unit_${unit}`]) return lvl[`unit_${unit}`];
  // Only fall back to level_5 if the requested level itself is unknown.
  if (!lvl) {
    return CURRICULUM_DATA.level_5[`unit_${unit}`] || CURRICULUM_DATA.level_5.unit_1;
  }
  // Requested level exists but unit missing → empty shell, no level_5 leak.
  return {
    title: "",
    icon: "",
    formToggleLabel: "",
    vocabulary: { lesson_1: [], lesson_5: [] },
    ai_speak: [],
    reading: { text: "Waiting for content update...", questions: [] },
    games: { grammar: [], phonics: { categories: [], words: [] } },
  };
}
